title: MouleHunterAI
description: Bot automatique pour dominer la course aux moules avec frites et bières

remote_theme: just-the-docs/just-the-docs

color_scheme: dark
just_the_docs:
  palette:
    primary: "#6b2d5c"
    accent: "#ff6b35ff"
  collections:
    docs:
      name: Documentation

search_enabled: true
heading_anchors: true
mermaid:
  version: "10.9.1"

aux_links:
  "GitHub →": "https://github.com/thenoob24/MouleHunter/"

collections:
  docs:
    permalink: "/:path/"
    output: true

defaults:
  - scope:
      path: "docs"
    values:
      layout: default
